// AUTO-GENERATED — do not edit manually.
// Run `node packages/pokemon-data/scripts/generate.mjs` to regenerate.

export interface PokemonBaseStats {
  hp: number;
  atk: number;
  def: number;
  spAtk: number;
  spDef: number;
  speed: number;
}

export interface PokemonData {
  id: number;
  name: string;
  types: string[];
  weight: number;   // kg
  height: number;   // m
  description: string;
  evolvesTo: number | null;
  evolveCandyCost: number | null;
  baseStats: PokemonBaseStats;
}

export const POKEMON: Record<number, PokemonData> = {
  1: {
    id: 1,
    name: "bulbasaur",
    types: ["grass","poison"],
    weight: 6.9,
    height: 0.7,
    description: "A strange seed was planted on its back at birth. The plant sprouts and grows with this POKéMON.",
    evolvesTo: 2,
    evolveCandyCost: 25,
    baseStats: { hp: 45, atk: 49, def: 49, spAtk: 65, spDef: 65, speed: 45 },
  },
  2: {
    id: 2,
    name: "ivysaur",
    types: ["grass","poison"],
    weight: 13,
    height: 1,
    description: "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.",
    evolvesTo: 3,
    evolveCandyCost: 100,
    baseStats: { hp: 60, atk: 62, def: 63, spAtk: 80, spDef: 80, speed: 60 },
  },
  3: {
    id: 3,
    name: "venusaur",
    types: ["grass","poison"],
    weight: 100,
    height: 2,
    description: "The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 80, atk: 82, def: 83, spAtk: 100, spDef: 100, speed: 80 },
  },
  4: {
    id: 4,
    name: "charmander",
    types: ["fire"],
    weight: 8.5,
    height: 0.6,
    description: "Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.",
    evolvesTo: 5,
    evolveCandyCost: 25,
    baseStats: { hp: 39, atk: 52, def: 43, spAtk: 60, spDef: 50, speed: 65 },
  },
  5: {
    id: 5,
    name: "charmeleon",
    types: ["fire"],
    weight: 19,
    height: 1.1,
    description: "When it swings its burning tail, it elevates the temperature to unbearably high levels.",
    evolvesTo: 6,
    evolveCandyCost: 100,
    baseStats: { hp: 58, atk: 64, def: 58, spAtk: 80, spDef: 65, speed: 80 },
  },
  6: {
    id: 6,
    name: "charizard",
    types: ["fire","flying"],
    weight: 90.5,
    height: 1.7,
    description: "Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 78, atk: 84, def: 78, spAtk: 109, spDef: 85, speed: 100 },
  },
  7: {
    id: 7,
    name: "squirtle",
    types: ["water"],
    weight: 9,
    height: 0.5,
    description: "After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth.",
    evolvesTo: 8,
    evolveCandyCost: 25,
    baseStats: { hp: 44, atk: 48, def: 65, spAtk: 50, spDef: 64, speed: 43 },
  },
  8: {
    id: 8,
    name: "wartortle",
    types: ["water"],
    weight: 22.5,
    height: 1,
    description: "Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance.",
    evolvesTo: 9,
    evolveCandyCost: 100,
    baseStats: { hp: 59, atk: 63, def: 80, spAtk: 65, spDef: 80, speed: 58 },
  },
  9: {
    id: 9,
    name: "blastoise",
    types: ["water"],
    weight: 85.5,
    height: 1.6,
    description: "A brutal POKéMON with pressurized water jets on its shell. They are used for high speed tackles.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 79, atk: 83, def: 100, spAtk: 85, spDef: 105, speed: 78 },
  },
  10: {
    id: 10,
    name: "caterpie",
    types: ["bug"],
    weight: 2.9,
    height: 0.3,
    description: "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.",
    evolvesTo: 11,
    evolveCandyCost: 25,
    baseStats: { hp: 45, atk: 30, def: 35, spAtk: 20, spDef: 20, speed: 45 },
  },
  11: {
    id: 11,
    name: "metapod",
    types: ["bug"],
    weight: 9.9,
    height: 0.7,
    description: "This POKéMON is vulnerable to attack while its shell is soft, exposing its weak and tender body.",
    evolvesTo: 12,
    evolveCandyCost: 100,
    baseStats: { hp: 50, atk: 20, def: 55, spAtk: 25, spDef: 25, speed: 30 },
  },
  12: {
    id: 12,
    name: "butterfree",
    types: ["bug","flying"],
    weight: 32,
    height: 1.1,
    description: "In battle, it flaps its wings at high speed to release highly toxic dust into the air.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 60, atk: 45, def: 50, spAtk: 90, spDef: 80, speed: 70 },
  },
  13: {
    id: 13,
    name: "weedle",
    types: ["bug","poison"],
    weight: 3.2,
    height: 0.3,
    description: "Often found in forests, eating leaves. It has a sharp venomous stinger on its head.",
    evolvesTo: 14,
    evolveCandyCost: 25,
    baseStats: { hp: 40, atk: 35, def: 30, spAtk: 20, spDef: 20, speed: 50 },
  },
  14: {
    id: 14,
    name: "kakuna",
    types: ["bug","poison"],
    weight: 10,
    height: 0.6,
    description: "Almost incapable of moving, this POKéMON can only harden its shell to protect itself from predators.",
    evolvesTo: 15,
    evolveCandyCost: 100,
    baseStats: { hp: 45, atk: 25, def: 50, spAtk: 25, spDef: 25, speed: 35 },
  },
  15: {
    id: 15,
    name: "beedrill",
    types: ["bug","poison"],
    weight: 29.5,
    height: 1,
    description: "It has three poisonous stingers on its forelegs and its tail. They are used to jab its enemy repeatedly.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 65, atk: 90, def: 40, spAtk: 45, spDef: 80, speed: 75 },
  },
  16: {
    id: 16,
    name: "pidgey",
    types: ["normal","flying"],
    weight: 1.8,
    height: 0.3,
    description: "A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand.",
    evolvesTo: 17,
    evolveCandyCost: 25,
    baseStats: { hp: 40, atk: 45, def: 40, spAtk: 35, spDef: 35, speed: 56 },
  },
  17: {
    id: 17,
    name: "pidgeotto",
    types: ["normal","flying"],
    weight: 30,
    height: 1.1,
    description: "Very protective of its sprawling territorial area, this POKéMON will fiercely peck at any intruder.",
    evolvesTo: 18,
    evolveCandyCost: 100,
    baseStats: { hp: 63, atk: 60, def: 55, spAtk: 50, spDef: 50, speed: 71 },
  },
  18: {
    id: 18,
    name: "pidgeot",
    types: ["normal","flying"],
    weight: 39.5,
    height: 1.5,
    description: "When hunting, it skims the surface of water at high speed to pick off unwary prey such as MAGIKARP.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 83, atk: 80, def: 75, spAtk: 70, spDef: 70, speed: 101 },
  },
  19: {
    id: 19,
    name: "rattata",
    types: ["normal"],
    weight: 3.5,
    height: 0.3,
    description: "Bites anything when it attacks. Small and very quick, it is a common sight in many places.",
    evolvesTo: 20,
    evolveCandyCost: 50,
    baseStats: { hp: 30, atk: 56, def: 35, spAtk: 25, spDef: 35, speed: 72 },
  },
  20: {
    id: 20,
    name: "raticate",
    types: ["normal"],
    weight: 18.5,
    height: 0.7,
    description: "It uses its whis­ kers to maintain its balance. It apparently slows down if they are cut off.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 55, atk: 81, def: 60, spAtk: 50, spDef: 70, speed: 97 },
  },
  21: {
    id: 21,
    name: "spearow",
    types: ["normal","flying"],
    weight: 2,
    height: 0.3,
    description: "It flaps its small wings busily to fly. Using its beak, it searches in grass for prey.",
    evolvesTo: 22,
    evolveCandyCost: 50,
    baseStats: { hp: 40, atk: 60, def: 30, spAtk: 31, spDef: 31, speed: 70 },
  },
  22: {
    id: 22,
    name: "fearow",
    types: ["normal","flying"],
    weight: 38,
    height: 1.2,
    description: "With its huge and magnificent wings, it can keep aloft without ever having to land for rest.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 65, atk: 90, def: 65, spAtk: 61, spDef: 61, speed: 100 },
  },
  23: {
    id: 23,
    name: "ekans",
    types: ["poison"],
    weight: 6.9,
    height: 2,
    description: "Moves silently and stealthily. Eats the eggs of birds, such as PIDGEY and SPEAROW, whole.",
    evolvesTo: 24,
    evolveCandyCost: 50,
    baseStats: { hp: 35, atk: 60, def: 44, spAtk: 40, spDef: 54, speed: 55 },
  },
  24: {
    id: 24,
    name: "arbok",
    types: ["poison"],
    weight: 65,
    height: 3.5,
    description: "It is rumored that the ferocious warning markings on its belly differ from area to area.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 60, atk: 95, def: 69, spAtk: 65, spDef: 79, speed: 80 },
  },
  25: {
    id: 25,
    name: "pikachu",
    types: ["electric"],
    weight: 6,
    height: 0.4,
    description: "When several of these POKéMON gather, their electricity could build and cause lightning storms.",
    evolvesTo: 26,
    evolveCandyCost: 100,
    baseStats: { hp: 35, atk: 55, def: 40, spAtk: 50, spDef: 50, speed: 90 },
  },
  26: {
    id: 26,
    name: "raichu",
    types: ["electric"],
    weight: 30,
    height: 0.8,
    description: "Its long tail serves as a ground to protect itself from its own high-voltage power.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 60, atk: 90, def: 55, spAtk: 90, spDef: 80, speed: 110 },
  },
  27: {
    id: 27,
    name: "sandshrew",
    types: ["ground"],
    weight: 12,
    height: 0.6,
    description: "Burrows deep underground in arid locations far from water. It only emerges to hunt for food.",
    evolvesTo: 28,
    evolveCandyCost: 50,
    baseStats: { hp: 50, atk: 75, def: 85, spAtk: 20, spDef: 30, speed: 40 },
  },
  28: {
    id: 28,
    name: "sandslash",
    types: ["ground"],
    weight: 29.5,
    height: 1,
    description: "Curls up into a spiny ball when threatened. It can roll while curled up to attack or escape.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 75, atk: 100, def: 110, spAtk: 45, spDef: 55, speed: 65 },
  },
  29: {
    id: 29,
    name: "nidoran-f",
    types: ["poison"],
    weight: 7,
    height: 0.4,
    description: "Although small, its venomous barbs render this POKéMON dangerous. The female has smaller horns.",
    evolvesTo: 30,
    evolveCandyCost: 25,
    baseStats: { hp: 55, atk: 47, def: 52, spAtk: 40, spDef: 40, speed: 41 },
  },
  30: {
    id: 30,
    name: "nidorina",
    types: ["poison"],
    weight: 20,
    height: 0.8,
    description: "The female's horn develops slowly. Prefers physical attacks such as clawing and biting.",
    evolvesTo: 31,
    evolveCandyCost: 100,
    baseStats: { hp: 70, atk: 62, def: 67, spAtk: 55, spDef: 55, speed: 56 },
  },
  31: {
    id: 31,
    name: "nidoqueen",
    types: ["poison","ground"],
    weight: 60,
    height: 1.3,
    description: "Its hard scales provide strong protection. It uses its hefty bulk to execute powerful moves.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 90, atk: 92, def: 87, spAtk: 75, spDef: 85, speed: 76 },
  },
  32: {
    id: 32,
    name: "nidoran-m",
    types: ["poison"],
    weight: 9,
    height: 0.5,
    description: "Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom.",
    evolvesTo: 33,
    evolveCandyCost: 25,
    baseStats: { hp: 46, atk: 57, def: 40, spAtk: 40, spDef: 40, speed: 50 },
  },
  33: {
    id: 33,
    name: "nidorino",
    types: ["poison"],
    weight: 19.5,
    height: 0.9,
    description: "An aggressive POKéMON that is quick to attack. The horn on its head secretes a powerful venom.",
    evolvesTo: 34,
    evolveCandyCost: 100,
    baseStats: { hp: 61, atk: 72, def: 57, spAtk: 55, spDef: 55, speed: 65 },
  },
  34: {
    id: 34,
    name: "nidoking",
    types: ["poison","ground"],
    weight: 62,
    height: 1.4,
    description: "It uses its powerful tail in battle to smash, constrict, then break the prey's bones.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 81, atk: 102, def: 77, spAtk: 85, spDef: 75, speed: 85 },
  },
  35: {
    id: 35,
    name: "clefairy",
    types: ["fairy"],
    weight: 7.5,
    height: 0.6,
    description: "Its magical and cute appeal has many admirers. It is rare and found only in certain areas.",
    evolvesTo: 36,
    evolveCandyCost: 100,
    baseStats: { hp: 70, atk: 45, def: 48, spAtk: 60, spDef: 65, speed: 35 },
  },
  36: {
    id: 36,
    name: "clefable",
    types: ["fairy"],
    weight: 40,
    height: 1.3,
    description: "A timid fairy POKéMON that is rarely seen. It will run and hide the moment it senses people.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 95, atk: 70, def: 73, spAtk: 95, spDef: 90, speed: 60 },
  },
  37: {
    id: 37,
    name: "vulpix",
    types: ["fire"],
    weight: 9.9,
    height: 0.6,
    description: "At the time of birth, it has just one tail. The tail splits from its tip as it grows older.",
    evolvesTo: 38,
    evolveCandyCost: 50,
    baseStats: { hp: 38, atk: 41, def: 40, spAtk: 50, spDef: 65, speed: 65 },
  },
  38: {
    id: 38,
    name: "ninetales",
    types: ["fire"],
    weight: 19.9,
    height: 1.1,
    description: "Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 73, atk: 76, def: 75, spAtk: 81, spDef: 100, speed: 100 },
  },
  39: {
    id: 39,
    name: "jigglypuff",
    types: ["normal","fairy"],
    weight: 5.5,
    height: 0.5,
    description: "When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep.",
    evolvesTo: 40,
    evolveCandyCost: 100,
    baseStats: { hp: 115, atk: 45, def: 20, spAtk: 45, spDef: 25, speed: 20 },
  },
  40: {
    id: 40,
    name: "wigglytuff",
    types: ["normal","fairy"],
    weight: 12,
    height: 1,
    description: "The body is soft and rubbery. When angered, it will suck in air and inflate itself to an enormous size.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 140, atk: 70, def: 45, spAtk: 85, spDef: 50, speed: 45 },
  },
  41: {
    id: 41,
    name: "zubat",
    types: ["poison","flying"],
    weight: 7.5,
    height: 0.8,
    description: "Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets.",
    evolvesTo: 42,
    evolveCandyCost: 25,
    baseStats: { hp: 40, atk: 45, def: 35, spAtk: 30, spDef: 40, speed: 55 },
  },
  42: {
    id: 42,
    name: "golbat",
    types: ["poison","flying"],
    weight: 55,
    height: 1.6,
    description: "Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 75, atk: 80, def: 70, spAtk: 65, spDef: 75, speed: 90 },
  },
  43: {
    id: 43,
    name: "oddish",
    types: ["grass","poison"],
    weight: 5.4,
    height: 0.5,
    description: "During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds.",
    evolvesTo: 44,
    evolveCandyCost: 25,
    baseStats: { hp: 45, atk: 50, def: 55, spAtk: 75, spDef: 65, speed: 30 },
  },
  44: {
    id: 44,
    name: "gloom",
    types: ["grass","poison"],
    weight: 8.6,
    height: 0.8,
    description: "The fluid that oozes from its mouth isn't drool. It is a nectar that is used to attract prey.",
    evolvesTo: 45,
    evolveCandyCost: 100,
    baseStats: { hp: 60, atk: 65, def: 70, spAtk: 85, spDef: 75, speed: 40 },
  },
  45: {
    id: 45,
    name: "vileplume",
    types: ["grass","poison"],
    weight: 18.6,
    height: 1.2,
    description: "It has the world’s largest petals. With every step, the petals shake out heavy clouds of toxic pollen.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 75, atk: 80, def: 85, spAtk: 110, spDef: 90, speed: 50 },
  },
  46: {
    id: 46,
    name: "paras",
    types: ["bug","grass"],
    weight: 5.4,
    height: 0.3,
    description: "Burrows to suck tree roots. The mushrooms on its back grow by draw­ ing nutrients from the bug host.",
    evolvesTo: 47,
    evolveCandyCost: 50,
    baseStats: { hp: 35, atk: 70, def: 55, spAtk: 45, spDef: 55, speed: 25 },
  },
  47: {
    id: 47,
    name: "parasect",
    types: ["bug","grass"],
    weight: 29.5,
    height: 1,
    description: "A host-parasite pair in which the parasite mushroom has taken over the host bug. Prefers damp places.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 60, atk: 95, def: 80, spAtk: 60, spDef: 80, speed: 30 },
  },
  48: {
    id: 48,
    name: "venonat",
    types: ["bug","poison"],
    weight: 30,
    height: 1,
    description: "Lives in the shadows of tall trees where it eats insects. It is attracted by light at night.",
    evolvesTo: 49,
    evolveCandyCost: 50,
    baseStats: { hp: 60, atk: 55, def: 50, spAtk: 40, spDef: 55, speed: 45 },
  },
  49: {
    id: 49,
    name: "venomoth",
    types: ["bug","poison"],
    weight: 12.5,
    height: 1.5,
    description: "The dustlike scales covering its wings are color-coded to indicate the kinds of poison it has.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 70, atk: 65, def: 60, spAtk: 90, spDef: 75, speed: 90 },
  },
  50: {
    id: 50,
    name: "diglett",
    types: ["ground"],
    weight: 0.8,
    height: 0.2,
    description: "Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground.",
    evolvesTo: 51,
    evolveCandyCost: 50,
    baseStats: { hp: 10, atk: 55, def: 25, spAtk: 35, spDef: 45, speed: 95 },
  },
  51: {
    id: 51,
    name: "dugtrio",
    types: ["ground"],
    weight: 33.3,
    height: 0.7,
    description: "A team of DIGLETT triplets. It triggers huge earthquakes by burrowing 60 miles underground.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 35, atk: 100, def: 50, spAtk: 50, spDef: 70, speed: 120 },
  },
  52: {
    id: 52,
    name: "meowth",
    types: ["normal"],
    weight: 4.2,
    height: 0.4,
    description: "It washes its face regularly to keep the coin on its forehead spotless. It doesn’t get along with Galarian Meowth.",
    evolvesTo: 53,
    evolveCandyCost: 50,
    baseStats: { hp: 40, atk: 45, def: 35, spAtk: 40, spDef: 40, speed: 90 },
  },
  53: {
    id: 53,
    name: "persian",
    types: ["normal"],
    weight: 32,
    height: 1,
    description: "Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 65, atk: 70, def: 60, spAtk: 65, spDef: 65, speed: 115 },
  },
  54: {
    id: 54,
    name: "psyduck",
    types: ["water"],
    weight: 19.6,
    height: 0.8,
    description: "While lulling its enemies with its vacant look, this wily POKéMON will use psychokinetic powers.",
    evolvesTo: 55,
    evolveCandyCost: 50,
    baseStats: { hp: 50, atk: 52, def: 48, spAtk: 65, spDef: 50, speed: 55 },
  },
  55: {
    id: 55,
    name: "golduck",
    types: ["water"],
    weight: 76.6,
    height: 1.7,
    description: "Often seen swim­ ming elegantly by lake shores. It is often mistaken for the Japanese monster, Kappa.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 80, atk: 82, def: 78, spAtk: 95, spDef: 80, speed: 85 },
  },
  56: {
    id: 56,
    name: "mankey",
    types: ["fighting"],
    weight: 28,
    height: 0.5,
    description: "Extremely quick to anger. It could be docile one moment then thrashing away the next instant.",
    evolvesTo: 57,
    evolveCandyCost: 25,
    baseStats: { hp: 40, atk: 80, def: 35, spAtk: 35, spDef: 45, speed: 70 },
  },
  57: {
    id: 57,
    name: "primeape",
    types: ["fighting"],
    weight: 32,
    height: 1,
    description: "Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 65, atk: 105, def: 60, spAtk: 60, spDef: 70, speed: 95 },
  },
  58: {
    id: 58,
    name: "growlithe",
    types: ["fire"],
    weight: 19,
    height: 0.7,
    description: "Very protective of its territory. It will bark and bite to repel intruders from its space.",
    evolvesTo: 59,
    evolveCandyCost: 50,
    baseStats: { hp: 55, atk: 70, def: 45, spAtk: 70, spDef: 50, speed: 60 },
  },
  59: {
    id: 59,
    name: "arcanine",
    types: ["fire"],
    weight: 155,
    height: 1.9,
    description: "A POKéMON that has been admired since the past for its beauty. It runs agilely as if on wings.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 90, atk: 110, def: 80, spAtk: 100, spDef: 80, speed: 95 },
  },
  60: {
    id: 60,
    name: "poliwag",
    types: ["water"],
    weight: 12.4,
    height: 0.6,
    description: "Its newly grown legs prevent it from running. It appears to prefer swimming than trying to stand.",
    evolvesTo: 61,
    evolveCandyCost: 25,
    baseStats: { hp: 40, atk: 50, def: 40, spAtk: 40, spDef: 40, speed: 90 },
  },
  61: {
    id: 61,
    name: "poliwhirl",
    types: ["water"],
    weight: 20,
    height: 1,
    description: "Capable of living in or out of water. When out of water, it sweats to keep its body slimy.",
    evolvesTo: 62,
    evolveCandyCost: 100,
    baseStats: { hp: 65, atk: 65, def: 65, spAtk: 50, spDef: 50, speed: 90 },
  },
  62: {
    id: 62,
    name: "poliwrath",
    types: ["water","fighting"],
    weight: 54,
    height: 1.3,
    description: "An adept swimmer at both the front crawl and breast stroke. Easily overtakes the best human swimmers.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 90, atk: 95, def: 95, spAtk: 70, spDef: 90, speed: 70 },
  },
  63: {
    id: 63,
    name: "abra",
    types: ["psychic"],
    weight: 19.5,
    height: 0.9,
    description: "Using its ability to read minds, it will identify impending danger and TELEPORT to safety.",
    evolvesTo: 64,
    evolveCandyCost: 25,
    baseStats: { hp: 25, atk: 20, def: 15, spAtk: 105, spDef: 55, speed: 90 },
  },
  64: {
    id: 64,
    name: "kadabra",
    types: ["psychic"],
    weight: 56.5,
    height: 1.3,
    description: "It emits special alpha waves from its body that induce headaches just by being close by.",
    evolvesTo: 65,
    evolveCandyCost: 100,
    baseStats: { hp: 40, atk: 35, def: 30, spAtk: 120, spDef: 70, speed: 105 },
  },
  65: {
    id: 65,
    name: "alakazam",
    types: ["psychic"],
    weight: 48,
    height: 1.5,
    description: "Its brain can out­ perform a super­ computer. Its intelligence quotient is said to be 5,000.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 55, atk: 50, def: 45, spAtk: 135, spDef: 95, speed: 120 },
  },
  66: {
    id: 66,
    name: "machop",
    types: ["fighting"],
    weight: 19.5,
    height: 0.8,
    description: "Loves to build its muscles. It trains in all styles of martial arts to become even stronger.",
    evolvesTo: 67,
    evolveCandyCost: 25,
    baseStats: { hp: 70, atk: 80, def: 50, spAtk: 35, spDef: 35, speed: 35 },
  },
  67: {
    id: 67,
    name: "machoke",
    types: ["fighting"],
    weight: 70.5,
    height: 1.5,
    description: "Its muscular body is so powerful, it must wear a power save belt to be able to regulate its motions.",
    evolvesTo: 68,
    evolveCandyCost: 100,
    baseStats: { hp: 80, atk: 100, def: 70, spAtk: 50, spDef: 60, speed: 45 },
  },
  68: {
    id: 68,
    name: "machamp",
    types: ["fighting"],
    weight: 130,
    height: 1.6,
    description: "Using its heavy muscles, it throws powerful punches that can send the victim clear over the horizon.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 90, atk: 130, def: 80, spAtk: 65, spDef: 85, speed: 55 },
  },
  69: {
    id: 69,
    name: "bellsprout",
    types: ["grass","poison"],
    weight: 4,
    height: 0.7,
    description: "A carnivorous POKéMON that traps and eats bugs. It uses its root feet to soak up needed moisture.",
    evolvesTo: 70,
    evolveCandyCost: 25,
    baseStats: { hp: 50, atk: 75, def: 35, spAtk: 70, spDef: 30, speed: 40 },
  },
  70: {
    id: 70,
    name: "weepinbell",
    types: ["grass","poison"],
    weight: 6.4,
    height: 1,
    description: "It spits out POISONPOWDER to immobilize the enemy and then finishes it with a spray of ACID.",
    evolvesTo: 71,
    evolveCandyCost: 100,
    baseStats: { hp: 65, atk: 90, def: 50, spAtk: 85, spDef: 45, speed: 55 },
  },
  71: {
    id: 71,
    name: "victreebel",
    types: ["grass","poison"],
    weight: 15.5,
    height: 1.7,
    description: "Said to live in huge colonies deep in jungles, although no one has ever returned from there.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 80, atk: 105, def: 65, spAtk: 100, spDef: 70, speed: 70 },
  },
  72: {
    id: 72,
    name: "tentacool",
    types: ["water","poison"],
    weight: 45.5,
    height: 0.9,
    description: "Drifts in shallow seas. Anglers who hook them by accident are often punished by its stinging acid.",
    evolvesTo: 73,
    evolveCandyCost: 50,
    baseStats: { hp: 40, atk: 40, def: 35, spAtk: 50, spDef: 100, speed: 70 },
  },
  73: {
    id: 73,
    name: "tentacruel",
    types: ["water","poison"],
    weight: 55,
    height: 1.6,
    description: "The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 80, atk: 70, def: 65, spAtk: 80, spDef: 120, speed: 100 },
  },
  74: {
    id: 74,
    name: "geodude",
    types: ["rock","ground"],
    weight: 20,
    height: 0.4,
    description: "Found in fields and mountains. Mistaking them for boulders, people often step or trip on them.",
    evolvesTo: 75,
    evolveCandyCost: 25,
    baseStats: { hp: 40, atk: 80, def: 100, spAtk: 30, spDef: 30, speed: 20 },
  },
  75: {
    id: 75,
    name: "graveler",
    types: ["rock","ground"],
    weight: 105,
    height: 1,
    description: "Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction.",
    evolvesTo: 76,
    evolveCandyCost: 100,
    baseStats: { hp: 55, atk: 95, def: 115, spAtk: 45, spDef: 45, speed: 35 },
  },
  76: {
    id: 76,
    name: "golem",
    types: ["rock","ground"],
    weight: 300,
    height: 1.4,
    description: "Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 80, atk: 120, def: 130, spAtk: 55, spDef: 65, speed: 45 },
  },
  77: {
    id: 77,
    name: "ponyta",
    types: ["fire"],
    weight: 30,
    height: 1,
    description: "Its hooves are 10 times harder than diamonds. It can trample anything completely flat in little time.",
    evolvesTo: 78,
    evolveCandyCost: 50,
    baseStats: { hp: 50, atk: 85, def: 55, spAtk: 65, spDef: 65, speed: 90 },
  },
  78: {
    id: 78,
    name: "rapidash",
    types: ["fire"],
    weight: 95,
    height: 1.7,
    description: "Very competitive, this POKéMON will chase anything that moves fast in the hopes of racing it.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 65, atk: 100, def: 70, spAtk: 80, spDef: 80, speed: 105 },
  },
  79: {
    id: 79,
    name: "slowpoke",
    types: ["water","psychic"],
    weight: 36,
    height: 1.2,
    description: "Incredibly slow and dopey. It takes 5 seconds for it to feel pain when under attack.",
    evolvesTo: 80,
    evolveCandyCost: 50,
    baseStats: { hp: 90, atk: 65, def: 65, spAtk: 40, spDef: 40, speed: 15 },
  },
  80: {
    id: 80,
    name: "slowbro",
    types: ["water","psychic"],
    weight: 78.5,
    height: 1.6,
    description: "The SHELLDER that is latched onto SLOWPOKE's tail is said to feed on the host's left over scraps.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 95, atk: 75, def: 110, spAtk: 100, spDef: 80, speed: 30 },
  },
  81: {
    id: 81,
    name: "magnemite",
    types: ["electric","steel"],
    weight: 6,
    height: 0.3,
    description: "Uses anti-gravity to stay suspended. Appears without warning and uses THUNDER WAVE and similar moves.",
    evolvesTo: 82,
    evolveCandyCost: 25,
    baseStats: { hp: 25, atk: 35, def: 70, spAtk: 95, spDef: 55, speed: 45 },
  },
  82: {
    id: 82,
    name: "magneton",
    types: ["electric","steel"],
    weight: 60,
    height: 1,
    description: "Formed by several MAGNEMITEs linked together. They frequently appear when sunspots flare up.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 50, atk: 60, def: 95, spAtk: 120, spDef: 70, speed: 70 },
  },
  83: {
    id: 83,
    name: "farfetchd",
    types: ["normal","flying"],
    weight: 15,
    height: 0.8,
    description: "The sprig of green onions it holds is its weapon. It is used much like a metal sword.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 52, atk: 90, def: 55, spAtk: 58, spDef: 62, speed: 60 },
  },
  84: {
    id: 84,
    name: "doduo",
    types: ["normal","flying"],
    weight: 39.2,
    height: 1.4,
    description: "A bird that makes up for its poor flying with its fast foot speed. Leaves giant footprints.",
    evolvesTo: 85,
    evolveCandyCost: 50,
    baseStats: { hp: 35, atk: 85, def: 45, spAtk: 35, spDef: 35, speed: 75 },
  },
  85: {
    id: 85,
    name: "dodrio",
    types: ["normal","flying"],
    weight: 85.2,
    height: 1.8,
    description: "Uses its three brains to execute complex plans. While two heads sleep, one head stays awake.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 60, atk: 110, def: 70, spAtk: 60, spDef: 60, speed: 110 },
  },
  86: {
    id: 86,
    name: "seel",
    types: ["water"],
    weight: 90,
    height: 1.1,
    description: "The protruding horn on its head is very hard. It is used for bashing through thick ice.",
    evolvesTo: 87,
    evolveCandyCost: 50,
    baseStats: { hp: 65, atk: 45, def: 55, spAtk: 45, spDef: 70, speed: 45 },
  },
  87: {
    id: 87,
    name: "dewgong",
    types: ["water","ice"],
    weight: 120,
    height: 1.7,
    description: "Stores thermal energy in its body. Swims at a steady 8 knots even in intensely cold waters.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 90, atk: 70, def: 80, spAtk: 70, spDef: 95, speed: 70 },
  },
  88: {
    id: 88,
    name: "grimer",
    types: ["poison"],
    weight: 30,
    height: 0.9,
    description: "Appears in filthy areas. Thrives by sucking up polluted sludge that is pumped out of factories.",
    evolvesTo: 89,
    evolveCandyCost: 50,
    baseStats: { hp: 80, atk: 80, def: 50, spAtk: 40, spDef: 50, speed: 25 },
  },
  89: {
    id: 89,
    name: "muk",
    types: ["poison"],
    weight: 30,
    height: 1.2,
    description: "Thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 105, atk: 105, def: 75, spAtk: 65, spDef: 100, speed: 50 },
  },
  90: {
    id: 90,
    name: "shellder",
    types: ["water"],
    weight: 4,
    height: 0.3,
    description: "Its hard shell repels any kind of attack. It is vulnerable only when its shell is open.",
    evolvesTo: 91,
    evolveCandyCost: 50,
    baseStats: { hp: 30, atk: 65, def: 100, spAtk: 45, spDef: 25, speed: 40 },
  },
  91: {
    id: 91,
    name: "cloyster",
    types: ["water","ice"],
    weight: 132.5,
    height: 1.5,
    description: "When attacked, it launches its horns in quick volleys. Its innards have never been seen.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 50, atk: 95, def: 180, spAtk: 85, spDef: 45, speed: 70 },
  },
  92: {
    id: 92,
    name: "gastly",
    types: ["ghost","poison"],
    weight: 0.1,
    height: 1.3,
    description: "Almost invisible, this gaseous POKéMON cloaks the target and puts it to sleep without notice.",
    evolvesTo: 93,
    evolveCandyCost: 25,
    baseStats: { hp: 30, atk: 35, def: 30, spAtk: 100, spDef: 35, speed: 80 },
  },
  93: {
    id: 93,
    name: "haunter",
    types: ["ghost","poison"],
    weight: 0.1,
    height: 1.6,
    description: "Because of its ability to slip through block walls, it is said to be from an­ other dimension.",
    evolvesTo: 94,
    evolveCandyCost: 100,
    baseStats: { hp: 45, atk: 50, def: 45, spAtk: 115, spDef: 55, speed: 95 },
  },
  94: {
    id: 94,
    name: "gengar",
    types: ["ghost","poison"],
    weight: 40.5,
    height: 1.5,
    description: "Under a full moon, this POKéMON likes to mimic the shadows of people and laugh at their fright.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 60, atk: 65, def: 60, spAtk: 130, spDef: 75, speed: 110 },
  },
  95: {
    id: 95,
    name: "onix",
    types: ["rock","ground"],
    weight: 210,
    height: 8.8,
    description: "As it grows, the stone portions of its body harden to become similar to a diamond, but colored black.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 35, atk: 45, def: 160, spAtk: 30, spDef: 45, speed: 70 },
  },
  96: {
    id: 96,
    name: "drowzee",
    types: ["psychic"],
    weight: 32.4,
    height: 1,
    description: "Puts enemies to sleep then eats their dreams. Occasionally gets sick from eating bad dreams.",
    evolvesTo: 97,
    evolveCandyCost: 50,
    baseStats: { hp: 60, atk: 48, def: 45, spAtk: 43, spDef: 90, speed: 42 },
  },
  97: {
    id: 97,
    name: "hypno",
    types: ["psychic"],
    weight: 75.6,
    height: 1.6,
    description: "When it locks eyes with an enemy, it will use a mix of PSI moves such as HYPNOSIS and CONFUSION.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 85, atk: 73, def: 70, spAtk: 73, spDef: 115, speed: 67 },
  },
  98: {
    id: 98,
    name: "krabby",
    types: ["water"],
    weight: 6.5,
    height: 0.4,
    description: "Its pincers are not only powerful weapons, they are used for balance when walking sideways.",
    evolvesTo: 99,
    evolveCandyCost: 50,
    baseStats: { hp: 30, atk: 105, def: 90, spAtk: 25, spDef: 25, speed: 50 },
  },
  99: {
    id: 99,
    name: "kingler",
    types: ["water"],
    weight: 60,
    height: 1.3,
    description: "The large pincer has 10000 hp of crushing power. However, its huge size makes it unwieldy to use.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 55, atk: 130, def: 115, spAtk: 50, spDef: 50, speed: 75 },
  },
  100: {
    id: 100,
    name: "voltorb",
    types: ["electric"],
    weight: 10.4,
    height: 0.5,
    description: "Usually found in power plants. Easily mistaken for a POKé BALL, they have zapped many people.",
    evolvesTo: 101,
    evolveCandyCost: 50,
    baseStats: { hp: 40, atk: 30, def: 50, spAtk: 55, spDef: 55, speed: 100 },
  },
  101: {
    id: 101,
    name: "electrode",
    types: ["electric"],
    weight: 66.6,
    height: 1.2,
    description: "It stores electric energy under very high pressure. It often explodes with little or no provocation.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 60, atk: 50, def: 70, spAtk: 80, spDef: 80, speed: 150 },
  },
  102: {
    id: 102,
    name: "exeggcute",
    types: ["grass","psychic"],
    weight: 2.5,
    height: 0.4,
    description: "Often mistaken for eggs. When disturbed, they quickly gather and attack in swarms.",
    evolvesTo: 103,
    evolveCandyCost: 50,
    baseStats: { hp: 60, atk: 40, def: 80, spAtk: 60, spDef: 45, speed: 40 },
  },
  103: {
    id: 103,
    name: "exeggutor",
    types: ["grass","psychic"],
    weight: 120,
    height: 2,
    description: "Legend has it that on rare occasions, one of its heads will drop off and continue on as an EXEGGCUTE.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 95, atk: 95, def: 85, spAtk: 125, spDef: 75, speed: 55 },
  },
  104: {
    id: 104,
    name: "cubone",
    types: ["ground"],
    weight: 6.5,
    height: 0.4,
    description: "Because it never removes its skull helmet, no one has ever seen this POKéMON's real face.",
    evolvesTo: 105,
    evolveCandyCost: 50,
    baseStats: { hp: 50, atk: 50, def: 95, spAtk: 40, spDef: 50, speed: 35 },
  },
  105: {
    id: 105,
    name: "marowak",
    types: ["ground"],
    weight: 45,
    height: 1,
    description: "The bone it holds is its key weapon. It throws the bone skillfully like a boomerang to KO targets.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 60, atk: 80, def: 110, spAtk: 50, spDef: 80, speed: 45 },
  },
  106: {
    id: 106,
    name: "hitmonlee",
    types: ["fighting"],
    weight: 49.8,
    height: 1.5,
    description: "When in a hurry, its legs lengthen progressively. It runs smoothly with extra long, loping strides.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 50, atk: 120, def: 53, spAtk: 35, spDef: 110, speed: 87 },
  },
  107: {
    id: 107,
    name: "hitmonchan",
    types: ["fighting"],
    weight: 50.2,
    height: 1.4,
    description: "While apparently doing nothing, it fires punches in lightning fast volleys that are impossible to see.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 50, atk: 105, def: 79, spAtk: 35, spDef: 110, speed: 76 },
  },
  108: {
    id: 108,
    name: "lickitung",
    types: ["normal"],
    weight: 65.5,
    height: 1.2,
    description: "Its tongue can be extended like a chameleon's. It leaves a tingling sensation when it licks enemies.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 90, atk: 55, def: 75, spAtk: 60, spDef: 75, speed: 30 },
  },
  109: {
    id: 109,
    name: "koffing",
    types: ["poison"],
    weight: 1,
    height: 0.6,
    description: "Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning.",
    evolvesTo: 110,
    evolveCandyCost: 50,
    baseStats: { hp: 40, atk: 65, def: 95, spAtk: 60, spDef: 45, speed: 35 },
  },
  110: {
    id: 110,
    name: "weezing",
    types: ["poison"],
    weight: 9.5,
    height: 1.2,
    description: "Where two kinds of poison gases meet, 2 KOFFINGs can fuse into a WEEZING over many years.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 65, atk: 90, def: 120, spAtk: 85, spDef: 70, speed: 60 },
  },
  111: {
    id: 111,
    name: "rhyhorn",
    types: ["ground","rock"],
    weight: 115,
    height: 1,
    description: "A POKéMON with a one-track mind. Once it charges,  it won't stop running until it falls asleep.",
    evolvesTo: 112,
    evolveCandyCost: 25,
    baseStats: { hp: 80, atk: 85, def: 95, spAtk: 30, spDef: 30, speed: 25 },
  },
  112: {
    id: 112,
    name: "rhydon",
    types: ["ground","rock"],
    weight: 120,
    height: 1.9,
    description: "Protected by an armor-like hide, it is capable of living in molten lava of 3,600 degrees.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 105, atk: 130, def: 120, spAtk: 45, spDef: 45, speed: 40 },
  },
  113: {
    id: 113,
    name: "chansey",
    types: ["normal"],
    weight: 34.6,
    height: 1.1,
    description: "A rare and elusive POKéMON that is said to bring happiness to those who manage to get it.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 250, atk: 5, def: 5, spAtk: 35, spDef: 105, speed: 50 },
  },
  114: {
    id: 114,
    name: "tangela",
    types: ["grass"],
    weight: 35,
    height: 1,
    description: "The whole body is swathed with wide vines that are similar to sea­ weed. Its vines shake as it walks.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 65, atk: 55, def: 115, spAtk: 100, spDef: 40, speed: 60 },
  },
  115: {
    id: 115,
    name: "kangaskhan",
    types: ["normal"],
    weight: 80,
    height: 2.2,
    description: "The infant rarely ventures out of its mother's protective pouch until it is 3 years old.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 105, atk: 95, def: 80, spAtk: 40, spDef: 80, speed: 90 },
  },
  116: {
    id: 116,
    name: "horsea",
    types: ["water"],
    weight: 8,
    height: 0.4,
    description: "Known to shoot down flying bugs with precision blasts of ink from the surface of the water.",
    evolvesTo: 117,
    evolveCandyCost: 25,
    baseStats: { hp: 30, atk: 40, def: 70, spAtk: 70, spDef: 25, speed: 60 },
  },
  117: {
    id: 117,
    name: "seadra",
    types: ["water"],
    weight: 25,
    height: 1.2,
    description: "Capable of swim­ ming backwards by rapidly flapping its wing-like pectoral fins and stout tail.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 55, atk: 65, def: 95, spAtk: 95, spDef: 45, speed: 85 },
  },
  118: {
    id: 118,
    name: "goldeen",
    types: ["water"],
    weight: 15,
    height: 0.6,
    description: "Its tail fin billows like an elegant ballroom dress, giving it the nickname of the Water Queen.",
    evolvesTo: 119,
    evolveCandyCost: 50,
    baseStats: { hp: 45, atk: 67, def: 60, spAtk: 35, spDef: 50, speed: 63 },
  },
  119: {
    id: 119,
    name: "seaking",
    types: ["water"],
    weight: 39,
    height: 1.3,
    description: "In the autumn spawning season, they can be seen swimming powerfully up rivers and creeks.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 80, atk: 92, def: 65, spAtk: 65, spDef: 80, speed: 68 },
  },
  120: {
    id: 120,
    name: "staryu",
    types: ["water"],
    weight: 34.5,
    height: 0.8,
    description: "If its body is torn, it can grow back if the red core remains. The core flashes at midnight.",
    evolvesTo: 121,
    evolveCandyCost: 50,
    baseStats: { hp: 30, atk: 45, def: 55, spAtk: 70, spDef: 55, speed: 85 },
  },
  121: {
    id: 121,
    name: "starmie",
    types: ["water","psychic"],
    weight: 80,
    height: 1.1,
    description: "Its central core glows with the seven colors of the rainbow. Some people value the core as a gem.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 60, atk: 75, def: 85, spAtk: 100, spDef: 85, speed: 115 },
  },
  122: {
    id: 122,
    name: "mr-mime",
    types: ["psychic","fairy"],
    weight: 54.5,
    height: 1.3,
    description: "If interrupted while it is miming, it will slap around the offender with its broad hands.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 40, atk: 45, def: 65, spAtk: 100, spDef: 120, speed: 90 },
  },
  123: {
    id: 123,
    name: "scyther",
    types: ["bug","flying"],
    weight: 56,
    height: 1.5,
    description: "With ninja-like agility and speed, it can create the illusion that there is more than one.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 70, atk: 110, def: 80, spAtk: 55, spDef: 80, speed: 105 },
  },
  124: {
    id: 124,
    name: "jynx",
    types: ["ice","psychic"],
    weight: 40.6,
    height: 1.4,
    description: "It seductively wiggles its hips as it walks. It can cause people to dance in unison with it.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 65, atk: 50, def: 35, spAtk: 115, spDef: 95, speed: 95 },
  },
  125: {
    id: 125,
    name: "electabuzz",
    types: ["electric"],
    weight: 30,
    height: 1.1,
    description: "Normally found near power plants, they can wander away and cause major blackouts in cities.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 65, atk: 83, def: 57, spAtk: 95, spDef: 85, speed: 105 },
  },
  126: {
    id: 126,
    name: "magmar",
    types: ["fire"],
    weight: 44.5,
    height: 1.3,
    description: "Its body always burns with an orange glow that enables it to hide perfectly among flames.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 65, atk: 95, def: 57, spAtk: 100, spDef: 85, speed: 93 },
  },
  127: {
    id: 127,
    name: "pinsir",
    types: ["bug"],
    weight: 55,
    height: 1.5,
    description: "If it fails to crush the victim in its pincers, it will swing it around and toss it hard.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 65, atk: 125, def: 100, spAtk: 55, spDef: 70, speed: 85 },
  },
  128: {
    id: 128,
    name: "tauros",
    types: ["normal"],
    weight: 88.4,
    height: 1.4,
    description: "When it targets an enemy, it charges furiously while whipping its body with its long tails.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 75, atk: 100, def: 95, spAtk: 40, spDef: 70, speed: 110 },
  },
  129: {
    id: 129,
    name: "magikarp",
    types: ["water"],
    weight: 10,
    height: 0.9,
    description: "In the distant past, it was somewhat stronger than the horribly weak descendants that exist today.",
    evolvesTo: 130,
    evolveCandyCost: 50,
    baseStats: { hp: 20, atk: 10, def: 55, spAtk: 15, spDef: 20, speed: 80 },
  },
  130: {
    id: 130,
    name: "gyarados",
    types: ["water","flying"],
    weight: 235,
    height: 6.5,
    description: "Once it begins to rampage, a GYARADOS will burn everything down, even in a harsh storm.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 95, atk: 125, def: 79, spAtk: 60, spDef: 100, speed: 81 },
  },
  131: {
    id: 131,
    name: "lapras",
    types: ["water","ice"],
    weight: 220,
    height: 2.5,
    description: "A POKéMON that has been over­ hunted almost to extinction. It can ferry people across the water.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 130, atk: 85, def: 80, spAtk: 85, spDef: 95, speed: 60 },
  },
  132: {
    id: 132,
    name: "ditto",
    types: ["normal"],
    weight: 4,
    height: 0.3,
    description: "Capable of copying an enemy's genetic code to instantly transform itself into a duplicate of the enemy.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 48, atk: 48, def: 48, spAtk: 48, spDef: 48, speed: 48 },
  },
  133: {
    id: 133,
    name: "eevee",
    types: ["normal"],
    weight: 6.5,
    height: 0.3,
    description: "Its genetic code is irregular. It may mutate if it is exposed to radiation from element STONEs.",
    evolvesTo: 134,
    evolveCandyCost: 50,
    baseStats: { hp: 55, atk: 55, def: 50, spAtk: 45, spDef: 65, speed: 55 },
  },
  134: {
    id: 134,
    name: "vaporeon",
    types: ["water"],
    weight: 29,
    height: 1,
    description: "Lives close to water. Its long tail is ridged with a fin which is often mistaken for a mermaid's.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 130, atk: 65, def: 60, spAtk: 110, spDef: 95, speed: 65 },
  },
  135: {
    id: 135,
    name: "jolteon",
    types: ["electric"],
    weight: 24.5,
    height: 0.8,
    description: "It accumulates negative ions in the atmosphere to blast out 10000- volt lightning bolts.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 65, atk: 65, def: 60, spAtk: 110, spDef: 95, speed: 130 },
  },
  136: {
    id: 136,
    name: "flareon",
    types: ["fire"],
    weight: 25,
    height: 0.9,
    description: "When storing thermal energy in its body, its temperature could soar to over 1600 degrees.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 65, atk: 130, def: 60, spAtk: 95, spDef: 110, speed: 65 },
  },
  137: {
    id: 137,
    name: "porygon",
    types: ["normal"],
    weight: 36.5,
    height: 0.8,
    description: "A POKéMON that consists entirely of programming code. Capable of moving freely in cyberspace.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 65, atk: 60, def: 70, spAtk: 85, spDef: 75, speed: 40 },
  },
  138: {
    id: 138,
    name: "omanyte",
    types: ["rock","water"],
    weight: 7.5,
    height: 0.4,
    description: "Although long extinct, in rare cases, it can be genetically resurrected from fossils.",
    evolvesTo: 139,
    evolveCandyCost: 50,
    baseStats: { hp: 35, atk: 40, def: 100, spAtk: 90, spDef: 55, speed: 35 },
  },
  139: {
    id: 139,
    name: "omastar",
    types: ["rock","water"],
    weight: 35,
    height: 1,
    description: "A prehistoric POKéMON that died out when its heavy shell made it impossible to catch prey.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 70, atk: 60, def: 125, spAtk: 115, spDef: 70, speed: 55 },
  },
  140: {
    id: 140,
    name: "kabuto",
    types: ["rock","water"],
    weight: 11.5,
    height: 0.5,
    description: "A POKéMON that was resurrected from a fossil found in what was once the ocean floor eons ago.",
    evolvesTo: 141,
    evolveCandyCost: 50,
    baseStats: { hp: 30, atk: 80, def: 90, spAtk: 55, spDef: 45, speed: 55 },
  },
  141: {
    id: 141,
    name: "kabutops",
    types: ["rock","water"],
    weight: 40.5,
    height: 1.3,
    description: "Its sleek shape is perfect for swim­ ming. It slashes prey with its claws and drains the body fluids.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 60, atk: 115, def: 105, spAtk: 65, spDef: 70, speed: 80 },
  },
  142: {
    id: 142,
    name: "aerodactyl",
    types: ["rock","flying"],
    weight: 59,
    height: 1.8,
    description: "A Pokémon that roamed the skies in the dinosaur era. Its teeth are like saw blades.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 80, atk: 105, def: 65, spAtk: 60, spDef: 75, speed: 130 },
  },
  143: {
    id: 143,
    name: "snorlax",
    types: ["normal"],
    weight: 460,
    height: 2.1,
    description: "Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 160, atk: 110, def: 65, spAtk: 65, spDef: 110, speed: 30 },
  },
  144: {
    id: 144,
    name: "articuno",
    types: ["ice","flying"],
    weight: 55.4,
    height: 1.7,
    description: "A legendary bird POKéMON that is said to appear to doomed people who are lost in icy mountains.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 90, atk: 85, def: 100, spAtk: 95, spDef: 125, speed: 85 },
  },
  145: {
    id: 145,
    name: "zapdos",
    types: ["electric","flying"],
    weight: 52.6,
    height: 1.6,
    description: "A legendary bird POKéMON that is said to appear from clouds while dropping enormous lightning bolts.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 90, atk: 90, def: 85, spAtk: 125, spDef: 90, speed: 100 },
  },
  146: {
    id: 146,
    name: "moltres",
    types: ["fire","flying"],
    weight: 60,
    height: 2,
    description: "Known as the legendary bird of fire. Every flap of its wings creates a dazzling flash of flames.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 90, atk: 100, def: 90, spAtk: 125, spDef: 85, speed: 90 },
  },
  147: {
    id: 147,
    name: "dratini",
    types: ["dragon"],
    weight: 3.3,
    height: 1.8,
    description: "Long considered a mythical POKéMON until recently when a small colony was found living underwater.",
    evolvesTo: 148,
    evolveCandyCost: 25,
    baseStats: { hp: 41, atk: 64, def: 45, spAtk: 50, spDef: 50, speed: 50 },
  },
  148: {
    id: 148,
    name: "dragonair",
    types: ["dragon"],
    weight: 16.5,
    height: 4,
    description: "A mystical POKéMON that exudes a gentle aura. Has the ability to change climate conditions.",
    evolvesTo: 149,
    evolveCandyCost: 100,
    baseStats: { hp: 61, atk: 84, def: 65, spAtk: 70, spDef: 70, speed: 70 },
  },
  149: {
    id: 149,
    name: "dragonite",
    types: ["dragon","flying"],
    weight: 210,
    height: 2.2,
    description: "An extremely rarely seen marine POKéMON. Its intelligence is said to match that of humans.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 91, atk: 134, def: 95, spAtk: 100, spDef: 100, speed: 80 },
  },
  150: {
    id: 150,
    name: "mewtwo",
    types: ["psychic"],
    weight: 122,
    height: 2,
    description: "It was created by a scientist after years of horrific gene splicing and DNA engineering experiments.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 106, atk: 110, def: 90, spAtk: 154, spDef: 90, speed: 130 },
  },
  151: {
    id: 151,
    name: "mew",
    types: ["psychic"],
    weight: 4,
    height: 0.4,
    description: "So rare that it is still said to be a mirage by many experts. Only a few people have seen it worldwide.",
    evolvesTo: null,
    evolveCandyCost: null,
    baseStats: { hp: 100, atk: 100, def: 100, spAtk: 100, spDef: 100, speed: 100 },
  }
};

/**
 * Synchronous Pokémon data lookup.
 * Returns the full data object for a Gen 1 Pokémon, or null if not found.
 */
export function getPokemonData(pokedexNumber: number): PokemonData | null {
  return POKEMON[pokedexNumber] ?? null;
}

/**
 * Get a Pokémon's display name, properly capitalized.
 */
export function getPokemonName(pokedexNumber: number): string {
  const data = POKEMON[pokedexNumber];
  if (!data) return `Pokemon #${pokedexNumber}`;
  
  // Handle Gen 1 special cases
  const name = data.name;
  if (name === "nidoran-f") return "Nidoran♀";
  if (name === "nidoran-m") return "Nidoran♂";
  if (name === "mr-mime") return "Mr. Mime";
  if (name === "farfetchd") return "Farfetch'd";
  
  return name.charAt(0).toUpperCase() + name.slice(1).replace(/-/g, " ");
}
